-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Country.Object.Continent exposing (code, name)

import Country.InputObject
import Country.Interface
import Country.Object
import Country.Scalar
import Country.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
code : SelectionSet (Maybe String) Country.Object.Continent
code =
    Object.selectionForField "code" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) Country.Object.Continent
name =
    Object.selectionForField "name" [] (Decode.string |> Decode.nullable)
