-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Country.Object.Language exposing (code, name, native, rtl)

import Country.InputObject
import Country.Interface
import Country.Object
import Country.Scalar
import Country.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
code : SelectionSet (Maybe String) Country.Object.Language
code =
    Object.selectionForField "code" [] (Decode.string |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) Country.Object.Language
name =
    Object.selectionForField "name" [] (Decode.string |> Decode.nullable)


{-| -}
native : SelectionSet (Maybe String) Country.Object.Language
native =
    Object.selectionForField "native" [] (Decode.string |> Decode.nullable)


{-| -}
rtl : SelectionSet (Maybe Int) Country.Object.Language
rtl =
    Object.selectionForField "rtl" [] (Decode.int |> Decode.nullable)
